### ISSUE TITLE
Ammo Mod doesn't save after using tombstone/whos whos and sometimes you loose the ammo mod

### ISSUE THREAD

**Issue by xMonologue** [whydoesanyonecare/T6_Zombies_aats#1]
For some reasons when player get their weapons back with tombstone or whos whos they loose their ammo mod and sometimes for unknown reasons the ammo mod just get removed like that. Any possibles fixes?

**Comment by whydoesanyonecare** [comment]
Who's who and Tombstone issues has been fixed.
